- name: Android Build, Sign & Release
  # You may pin to the exact commit or the version.
  # uses: FreetimeMaker/android-ci-action@e7ade07b0b685a6fe6392d72a331909179bf14fc
  uses: FreetimeMaker/android-ci-action@v1.2.0
  with:
    # Base64 encoded keystore (ignored if use_repo_keystore=true)
    keystore: # optional
    # 
    keystore_password: 
    # 
    key_alias: 
    # 
    key_password: 
    # Gradle task to run
    gradle_task: # optional, default is assembleRelease
    # Use a keystore stored in the repository
    use_repo_keystore: # optional, default is false
    # Path to the repo keystore
    repo_keystore_path: # optional, default is release-key.jks
    # Automatically create git tag based on versionName
    auto_tag: # optional, default is true
    # Enable VirusTotal scanning before signing
    virustotal_scan: # optional, default is false
    # VirusTotal API key
    virustotal_api_key: # optional
    # Max seconds to wait for VirusTotal analysis
    virustotal_timeout: # optional, default is 120
